# Generated by Django 5.0.7 on 2024-07-30 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('employer_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('Job Seeker', 'Job Seeker'), ('Employer', 'Employer'), ('Admin', 'Admin')], max_length=20)),
                ('profile_picture', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=50)),
                ('culture_description', models.TextField()),
                ('logo_url', models.CharField(max_length=255)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.employer')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('benefits', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('application_deadline', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.employer')),
            ],
        ),
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('analytics_id', models.AutoField(primary_key=True, serialize=False)),
                ('views', models.IntegerField()),
                ('applications', models.IntegerField()),
                ('matches', models.IntegerField()),
                ('average_time_to_hire', models.IntegerField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.job')),
            ],
        ),
        migrations.CreateModel(
            name='TalentPool',
            fields=[
                ('pool_id', models.AutoField(primary_key=True, serialize=False)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.employer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('resume_id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_summary', models.TextField()),
                ('education', models.TextField()),
                ('experience', models.TextField()),
                ('skills', models.TextField()),
                ('certifications', models.TextField()),
                ('contact_info', models.TextField()),
                ('video_resume_url', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='jobapp.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='jobapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('match_score', models.IntegerField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=255)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='employer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobapp.user'),
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('assessment_id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_test_url', models.CharField(max_length=255)),
                ('score', models.IntegerField()),
                ('assessment_date', models.DateTimeField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('cover_letter', models.TextField()),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.job')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('permissions', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobapp.user')),
            ],
        ),
    ]
